steps:
- name: 'node:14'
  args: ['npm', 'install']
  dir: './'
- name: 'node:14'
  args: ['npm', 'run', 'build']
  dir: './'
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['app', 'deploy']
timeout: '1600s'
